[package]
name = "writeahead"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
thiserror = "2.0.9"

[dev-dependencies]
tempfile = "3.14.0"

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.7.2"
libc = "0.2.167"
tokio = { version = "1.42.0", features = ["full"] }
